In [35]:
import pandas as pd
from dbfread import DBF

In [36]:
dfData = pd.DataFrame([
    ['RTP32v900'    , r"E:\GitHub\WF-TDM-v9x\Scenarios\v9.0 - official\RTP_2032\4_ModeChoice\3_TransitAssign\_v9_SE32_Net32_2_OD_Station.dbf"],
    ['RTP_2032_SLC', r"T:\WF-TDM-v9x\Scenarios\v9_SLC_TransitAnalysis\RTP_2032_SLC\4_ModeChoice\3_TransitAssign\_v9_SE32_HWY32_SLCoTransit50_2_OD_Station.dbf"],
    ['RTP_2032_SLC_Select'  , r"T:\WF-TDM-v9x\Scenarios\v9_SLC_TransitAnalysis\RTP_2032_SLC_Select\4_ModeChoice\3_TransitAssign\_v9_SE32_HWY32_SLCoTr50Sct_2_OD_Station.dbf"  ],
    ['RTP_2032_SLCo_Phase3' , r"T:\WF-TDM-v9x\Scenarios\v9_SLC_TransitAnalysis\RTP_2032_SLCo_Phase3\4_ModeChoice\3_TransitAssign\_v9_SE32_HWY32_SLCoTr50SLCo_2_OD_Station.dbf"],
], columns=['scenario','filename'])
dfData

               scenario                                           filename
0             RTP32v900  E:\GitHub\WF-TDM-v9x\Scenarios\v9.0 - official...
1          RTP_2032_SLC  T:\WF-TDM-v9x\Scenarios\v9_SLC_TransitAnalysis...
2   RTP_2032_SLC_Select  T:\WF-TDM-v9x\Scenarios\v9_SLC_TransitAnalysis...
3  RTP_2032_SLCo_Phase3  T:\WF-TDM-v9x\Scenarios\v9_SLC_TransitAnalysis...

In [38]:
# List to hold the data from each file
all_data = []

# Iterate over the DataFrame
for _, row in dfData.iterrows():

    # Load the DBF file
    table = DBF(row['filename'], load=True)  # Set load=True to load all records into memory
    
    # Convert to DataFrame
    temp_df = pd.DataFrame(iter(table))

    # Add the 'Scenario' column to the DataFrame
    temp_df['scenario'] = row['scenario']
    
    # Append to the list
    all_data.append(temp_df)

# Concatenate all the DataFrames in the list
final_df = pd.concat(all_data, ignore_index=True)

# Display the resulting DataFrame
display(final_df)

,MODE,NAMEID,NAME,OPERATOR,ONEWAY,LINKSEQ1,LINKSEQ2,A,STOP_NAME,DIST,...,DY_W_BRD2,DY_BOARD2,DY_ALIGHT2,DY_RIDERS2,TOT_DRIVE,TOT_WALK,TOT_BOARD,TOT_ALIGHT,TOT_RIDERS,scenario
0,4,1.0,Cedar_Exp,0,1,1,0,50035,,5.82,...,0.00,0.00,0.80,0.80,0.22,0.58,0.80,0.80,1.60,RTP32v900
1,4,1.0,Cedar_Exp,0,1,31,131,62317,,3.52,...,0.04,0.04,0.23,0.98,0.20,0.07,0.28,0.28,1.97,RTP32v900
2,4,1.0,Cedar_Exp,0,1,51,111,69027,,4.20,...,0.67,0.67,0.33,0.65,0.21,0.79,1.00,1.00,1.30,RTP32v900
3,4,1.0,Cedar_Exp,0,1,72,90,68231,,2.13,...,0.22,0.22,1.23,1.66,0.00,1.44,1.44,1.44,3.31,RTP32v900
4,4,1.0,Cedar_Exp,0,1,81,81,67852,,2.13,...,1.65,1.65,0.99,1.00,0.19,2.45,2.64,2.64,2.00,RTP32v900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14417,9,101.0,UVX,0,0,119,19,67620,,0.41,...,40.32,40.32,5.07,134.96,0.00,45.39,45.39,45.39,269.92,RTP_2032_SLCo_Phase3
14418,9,101.0,UVX,0,0,123,15,67702,,0.47,...,26.14,26.14,32.33,141.15,0.00,58.47,58.47,58.47,282.30,RTP_2032_SLCo_Phase3
14419,9,101.0,UVX,0,0,127,11,67764,,0.52,...,35.60,35.60,133.91,239.46,0.00,169.51,169.51,169.51,478.92,RTP_2032_SLCo_Phase3
14420,9,101.0,UVX,0,0,131,7,67859,,1.13,...,58.81,58.81,46.01,226.66,0.00,104.82,104.82,104.82,453.33,RTP_2032_SLCo_Phase3
14421,9,101.0,UVX,0,0,0,1,50030,,0.00,...,226.66,226.66,0.00,0.00,0.00,226.66,226.66,226.66,0.00,RTP_2032_SLCo_Phase3

In [41]:

# Path to the DBF file
dbf_path = r"T:\WF-TDM-v9x\Scenarios\v9_SLC_TransitAnalysis\RTP_2032_SLCo_Phase3\0_InputProcessing\UpdatedMasterNet\GIS\MasterNet_v9 - 2023-09-16 - Node.dbf"

# Load the DBF file
table = DBF(dbf_path, load=True)  # Set load=True to load all records into memory

# Convert to DataFrame
df_nodes = pd.DataFrame(iter(table))

# Display the DataFrame
display(df_nodes)

,N,X,Y,GEOGKEY,EXTERNAL,MAG_NODE,HOTZN,TAZID,NODENAME,PNR_2015,...,FARZN_2021,FARZN_2023,FARZN_2024,FARZN_2028,FARZN23_32,FARZN23_42,FARZN23_50,FARE23_32U,FARE23_42U,FARE23_50U
0,1,411935.0000,4605642.000,411935_4605642,0,0,0,1,,0,...,0,0,0,0,0,0,0,0,0,0
1,2,412641.0000,4606013.000,412641_4606013,0,0,0,2,,0,...,0,0,0,0,0,0,0,0,0,0
2,3,408993.0000,4603544.000,408993_4603544,0,0,0,3,,0,...,0,0,0,0,0,0,0,0,0,0
3,4,410051.0000,4604806.000,410051_4604806,0,0,0,4,,0,...,0,0,0,0,0,0,0,0,0,0
4,5,413394.0000,4603600.000,413394_4603600,0,0,0,5,,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21274,95061,431050.6881,4422110.715,431050_4422110,0,1,0,3469,,0,...,0,0,0,0,0,0,0,0,0,0
21275,95062,430713.6121,4421517.072,430713_4421517,0,1,0,3469,,0,...,0,0,0,0,0,0,0,0,0,0
21276,95063,452850.1772,4468529.559,452850_4468529,0,1,0,3508,,0,...,0,0,0,0,0,0,0,0,0,0
21277,95064,473181.5500,4444171.200,473181_4444171,0,1,0,3536,,0,...,0,0,0,0,0,0,0,0,0,0
21278,95065,480730.7100,4444037.000,480730_4444037,0,1,0,3536,,0,...,0,0,0,0,0,0,0,0,0,0

In [45]:
df_data_on_nodes = pd.merge(df_nodes, final_df, left_on='N', right_on='A')
df_data_on_nodes

,N,X,Y,GEOGKEY,EXTERNAL,MAG_NODE,HOTZN,TAZID,NODENAME,PNR_2015,...,DY_W_BRD2,DY_BOARD2,DY_ALIGHT2,DY_RIDERS2,TOT_DRIVE,TOT_WALK,TOT_BOARD,TOT_ALIGHT,TOT_RIDERS,scenario
0,10008,423401.1517,4485422.991,423401_4485422,0,0,0,2117,Draper,40,...,0.00,0.00,41.05,41.04,13.68,27.37,41.05,41.05,82.08,RTP32v900
1,10008,423401.1517,4485422.991,423401_4485422,0,0,0,2117,Draper,40,...,55.98,405.77,1029.43,8441.10,1124.61,310.59,1435.20,1435.20,16882.20,RTP32v900
2,10008,423401.1517,4485422.991,423401_4485422,0,0,0,2117,Draper,40,...,116.43,116.43,61.77,61.76,17.80,160.40,178.19,178.19,123.53,RTP32v900
3,10008,423401.1517,4485422.991,423401_4485422,0,0,0,2117,Draper,40,...,0.00,0.00,14.18,14.17,3.83,10.35,14.18,14.18,28.34,RTP_2032_SLC
4,10008,423401.1517,4485422.991,423401_4485422,0,0,0,2117,Draper,40,...,0.00,0.00,329.02,329.02,127.42,201.61,329.02,329.02,658.04,RTP_2032_SLC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14417,90130,445663.9000,4493357.700,445663_4493357,0,0,0,2196,,0,...,1.14,1.14,0.00,-0.00,0.00,1.14,1.14,1.14,-0.01,RTP_2032_SLCo_Phase3
14418,90131,448079.6000,4492317.100,448079_4492317,0,0,0,2215,,0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,RTP32v900
14419,90131,448079.6000,4492317.100,448079_4492317,0,0,0,2215,,0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,RTP_2032_SLC
14420,90131,448079.6000,4492317.100,448079_4492317,0,0,0,2215,,0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,RTP_2032_SLC_Select
14421,90131,448079.6000,4492317.100,448079_4492317,0,0,0,2215,,0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,RTP_2032_SLCo_Phase3

In [46]:
from dbfread import DBF

# Path to the DBF file
dbf_path = r"T:\WF-TDM-v9x\1_Inputs\1_TAZ\TAZ.dbf"

# Load the DBF file
table = DBF(dbf_path, load=True)  # Set load=True to load all records into memory

# Convert to DataFrame
df_taz = pd.DataFrame(iter(table))

# Display the DataFrame
display(df_taz)

,TAZID,TAZID_V832,SORT,CO_IDX,CO_TAZID,SUBAREAID,ACRES,DEVACRES,DEVPBLEPCT,X,...,DISTSML,DSML_NAME,CBD,TERMTIME,PRKCSTPERM,PRKCSTTEMP,WALK100,ECOEDPASS,FREEFARE,REMM
0,1,8,1,1,30001,1,582.086695,582.086695,1.00,412339.399850,...,1,Box Elder County - North,0,0,0.0,0.0,0,0,0,0
1,2,9,2,2,30002,1,135.465050,134.110399,0.99,412640.145346,...,1,Box Elder County - North,0,0,0.0,0.0,0,0,0,0
2,3,2,3,3,30003,1,663.377323,636.842231,0.96,408992.313015,...,1,Box Elder County - North,0,0,0.0,0.0,0,0,0,0
3,4,1,4,4,30004,1,375.207672,371.455595,0.99,410102.680272,...,1,Box Elder County - North,0,0,0.0,0.0,0,0,0,0
4,5,10,5,5,30005,1,1031.463233,1021.148600,0.99,413392.938145,...,1,Box Elder County - North,0,0,0.0,0.0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3541,3506,0,3542,1290,491290,1,329.216986,55.966888,0.17,451765.414346,...,101,Eastside Mountains,0,0,0.0,0.0,0,0,0,0
3542,3508,0,3543,1292,491292,1,3449.109810,1207.188434,0.35,450266.978619,...,101,Eastside Mountains,0,0,0.0,0.0,0,0,0,0
3543,3504,0,3544,1288,491288,1,1203.759358,288.902246,0.24,449014.603321,...,101,Eastside Mountains,0,0,0.0,0.0,0,0,0,0
3544,3546,0,3545,1330,491330,1,59358.376922,40957.280076,0.69,499554.707547,...,101,Eastside Mountains,0,0,0.0,0.0,0,0,0,0
3545,3507,0,3546,1291,491291,1,2360.868265,708.260480,0.30,455050.550532,...,101,Eastside Mountains,0,0,0.0,0.0,0,0,0,0

In [29]:
df_taz['TAZID']

0          1
1          2
2          3
3          4
4          5
        ...
3541    3506
3542    3508
3543    3504
3544    3546
3545    3507
Name: TAZID, Length: 3546, dtype: int64

In [47]:
df_data_on_nodes_with_taz = pd.merge(df_data_on_nodes, df_taz, on='TAZID')
df_data_on_nodes_with_taz

,N,X_x,Y_x,GEOGKEY,EXTERNAL,MAG_NODE,HOTZN,TAZID,NODENAME,PNR_2015,...,DISTSML,DSML_NAME,CBD,TERMTIME,PRKCSTPERM,PRKCSTTEMP,WALK100,ECOEDPASS,FREEFARE,REMM
0,10008,423401.1517,4485422.991,423401_4485422,0,0,0,2117,Draper,40,...,69,Draper,0,0,0.0,0.0,0,0,0,1
1,10008,423401.1517,4485422.991,423401_4485422,0,0,0,2117,Draper,40,...,69,Draper,0,0,0.0,0.0,0,0,0,1
2,10008,423401.1517,4485422.991,423401_4485422,0,0,0,2117,Draper,40,...,69,Draper,0,0,0.0,0.0,0,0,0,1
3,10008,423401.1517,4485422.991,423401_4485422,0,0,0,2117,Draper,40,...,69,Draper,0,0,0.0,0.0,0,0,0,1
4,10008,423401.1517,4485422.991,423401_4485422,0,0,0,2117,Draper,40,...,69,Draper,0,0,0.0,0.0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14417,90130,445663.9000,4493357.700,445663_4493357,0,0,0,2196,,0,...,61,Alta,0,0,0.0,0.0,0,0,0,0
14418,90131,448079.6000,4492317.100,448079_4492317,0,0,0,2215,,0,...,61,Alta,0,0,0.0,0.0,0,0,0,0
14419,90131,448079.6000,4492317.100,448079_4492317,0,0,0,2215,,0,...,61,Alta,0,0,0.0,0.0,0,0,0,0
14420,90131,448079.6000,4492317.100,448079_4492317,0,0,0,2215,,0,...,61,Alta,0,0,0.0,0.0,0,0,0,0
14421,90131,448079.6000,4492317.100,448079_4492317,0,0,0,2215,,0,...,61,Alta,0,0,0.0,0.0,0,0,0,0

In [53]:
df_data_on_nodes_with_taz.groupby(['CO_FIPS','scenario'], as_index=False).agg(board=('TOT_BOARD','sum')).pivot(index='CO_FIPS',values='board',columns='scenario')

scenario  RTP32v900  RTP_2032_SLC  RTP_2032_SLC_Select  RTP_2032_SLCo_Phase3
CO_FIPS
3            181.21        182.49               181.20                181.20
11         11255.01      14420.68             11535.20              12776.52
35        204998.77     233325.05            219761.46             240069.33
49         39768.23      44566.11             40138.93              44562.39
57         10231.90      12645.54             10392.94              10426.51